export const firstImage = "https://askproject.net/chloro/wp-content/uploads/sites/23/2021/12/anthony-tran-Sd9A6NVHsd4-unsplash3.jpeg"
 export const secondImage="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/12/kalos-skincare-jyKa0Ynxvow-unsplash.jpeg";
export const thirdImage="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/woman-in-towel-applying-body-cream-with-hands-loti-XNNXLFD.jpg"
export const productImage="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/composition-of-a-brown-glass-dropper-bottle-with-a-NWSPPKG.jpg";
export const productImage2="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/cosmetic-bottle-with-serum-or-hyaluronic-acid-and-YPT8W8X-1024x1024.jpg";
// export const bgColor=#023a15;
export const circleImage="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/Asset-6_2-1536x379.png";
export const featureImage1="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/lifting-anti-wrinkle-collagen-patches-under-eyes-RB522JG.jpg"
export const featureImage2="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/top-view-of-coconut-oil-in-bottle-on-coconut-half-VTN4936.jpg"
export const featureImage3="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/cosmetic-bottle-with-serum-or-hyaluronic-acid-and-YPT8W8X-1024x1024.jpg";
export const serviceImage1="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/woman-relaxing-with-a-facial-mask-at-the-spa-FT2XZH6.jpg";
export const serviceImage2="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/facial-massage-beauty-treatment-CV8BDTP.jpg";
export const serviceImage3="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/massage-therapist-massaging-woman-AWN6QAT.jpg ";
export const serviceImage4="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/close-up-of-cosmetic-botox-injection-RGZTDV3.jpg ";
export const serviceImage5="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/pedicure-LDJ5TEU.jpg";
export const serviceImage6="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/facial-beauty-treatment-in-spa-CSVTMH2.jpg";
export const reviewImage="https://askproject.net/chloro/wp-content/uploads/sites/23/2021/08/brown-D9SR4HS-800x400.jpg";